export type TravelPackage = {
    id: number;
    title: string;
    description: string;
    image: string;
    vehicleType: string;
    duration: number;
    maxPeople: number;
    confirmedPeople: number;
    originalPrice: number;
    price: number;
    packageTax: number;
    cupomDiscount?: string;
    discountValue?: number;
    manualDiscountValue?: number;
    startDate: string;
    isAvailable: boolean;
    originCity: string;
    originCountry: string;
    destinationCity: string;
    destinationCountry: string;
    createdAt: string;
    isActive: boolean;
};